name: HiTaxon
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - art=2016.06.05
  - bioconductor-polyester=1.36
  - biopython=1.81
  - cd-hit=4.8.1
  - ete3=3.1.3
  - kaiju=1.9.2
  - kraken2=2.1.2
  - fastani=1.33
  - fastp=0.23.3
  - fastq-join=1.3.1
  - fasttext=0.9.2
  - ncbi-datasets-cli=15.3.1
  - numpy=1.25.0
  - pandas=1.5.3
  - prodigal=2.6.3
  - scikit-learn=1.1.3
  - seqkit=2.4.0
  - seqtk=1.3
  - tqdm=4.65.0
